-- ============================================================
-- OBSERVATÓRIO ELEITORAL
-- MODELO HISTÓRICO TSE + POWER BI
--
-- Estratégia:
-- 1. Não apagar tabelas existentes.
-- 2. Criar uma camada dimensional.
-- 3. Criar fatos de votação.
-- 4. Preservar arquivos brutos do TSE.
-- 5. Preparar views para Power BI.
-- ============================================================


-- ============================================================
-- 1. ELEIÇÃO
-- ============================================================

create table if not exists public.dim_eleicao (
    id bigint generated by default as identity primary key,

    ano integer not null,

    codigo_tse text,

    nome text not null,

    tipo text,

    inicio date,

    fim date,

    ambiente text not null default 'oficial'
        check (
            ambiente in (
                'demo',
                'simulado',
                'oficial'
            )
        ),

    fonte text not null default 'TSE',

    criado_em timestamptz not null default now(),

    atualizado_em timestamptz not null default now(),

    unique (
        ano,
        codigo_tse,
        ambiente
    )
);


-- ============================================================
-- 2. PLEITO
-- ============================================================

create table if not exists public.dim_pleito (
    id bigint generated by default as identity primary key,

    eleicao_id bigint not null
        references public.dim_eleicao(id)
        on delete cascade,

    codigo_tse text,

    codigo_turno text,

    numero_turno integer,

    codigo_tipo text,

    nome text,

    cargo text,

    criado_em timestamptz not null default now(),

    unique (
        eleicao_id,
        codigo_tse
    )
);


-- ============================================================
-- 3. UF
-- ============================================================

create table if not exists public.dim_uf (
    id bigint generated by default as identity primary key,

    sigla text not null,

    nome text not null,

    codigo_tse text,

    codigo_ibge text,

    criado_em timestamptz not null default now(),

    unique (
        sigla
    ),

    unique (
        codigo_ibge
    )
);


-- ============================================================
-- 4. MUNICÍPIO
-- ============================================================

create table if not exists public.dim_municipio (
    id bigint generated by default as identity primary key,

    uf_id bigint not null
        references public.dim_uf(id)
        on delete restrict,

    codigo_tse text,

    codigo_ibge text,

    nome text not null,

    criado_em timestamptz not null default now(),

    unique (
        uf_id,
        codigo_ibge
    )
);


-- ============================================================
-- 5. ZONA
-- ============================================================

create table if not exists public.dim_zona (
    id bigint generated by default as identity primary key,

    municipio_id bigint not null
        references public.dim_municipio(id)
        on delete restrict,

    numero integer not null,

    criado_em timestamptz not null default now(),

    unique (
        municipio_id,
        numero
    )
);


-- ============================================================
-- 6. SEÇÃO
-- ============================================================

create table if not exists public.dim_secao (
    id bigint generated by default as identity primary key,

    zona_id bigint not null
        references public.dim_zona(id)
        on delete restrict,

    numero integer not null,

    localidade_id bigint,

    criado_em timestamptz not null default now(),

    unique (
        zona_id,
        numero
    )
);


-- ============================================================
-- 7. PARTIDO
-- ============================================================

create table if not exists public.dim_partido (
    id bigint generated by default as identity primary key,

    numero integer,

    sigla text,

    nome text not null,

    codigo_tse text,

    criado_em timestamptz not null default now(),

    atualizado_em timestamptz not null default now()
);


-- ============================================================
-- 8. CANDIDATO
-- ============================================================

create table if not exists public.dim_candidato (
    id bigint generated by default as identity primary key,

    eleicao_id bigint not null
        references public.dim_eleicao(id)
        on delete cascade,

    partido_id bigint
        references public.dim_partido(id)
        on delete restrict,

    numero integer not null,

    nome text,

    nome_urna text,

    cargo text,

    codigo_tse text,

    criado_em timestamptz not null default now(),

    unique (
        eleicao_id,
        numero,
        cargo
    )
);


-- ============================================================
-- 9. ARQUIVOS BRUTOS TSE
-- ============================================================

create table if not exists public.raw_arquivos_tse (
    id bigint generated by default as identity primary key,

    eleicao_id bigint
        references public.dim_eleicao(id)
        on delete restrict,

    pleito_id bigint
        references public.dim_pleito(id)
        on delete restrict,

    tipo_arquivo text not null,

    nome_arquivo text,

    url_origem text,

    idg text,

    etag text,

    last_modified text,

    sha256 text not null,

    conteudo_json jsonb not null,

    recebido_em timestamptz not null default now(),

    processado_em timestamptz,

    status text not null default 'recebido'
        check (
            status in (
                'recebido',
                'processando',
                'processado',
                'erro',
                'ignorado'
            )
        ),

    erro text,

    unique (
        sha256
    )
);


-- ============================================================
-- 10. FATO DE VOTAÇÃO
-- ============================================================

create table if not exists public.fact_votacao (
    id bigint generated by default as identity primary key,

    eleicao_id bigint not null
        references public.dim_eleicao(id)
        on delete restrict,

    pleito_id bigint
        references public.dim_pleito(id)
        on delete restrict,

    candidato_id bigint not null
        references public.dim_candidato(id)
        on delete restrict,

    uf_id bigint
        references public.dim_uf(id)
        on delete restrict,

    municipio_id bigint
        references public.dim_municipio(id)
        on delete restrict,

    zona_id bigint
        references public.dim_zona(id)
        on delete restrict,

    secao_id bigint
        references public.dim_secao(id)
        on delete restrict,

    raw_arquivo_id bigint
        references public.raw_arquivos_tse(id)
        on delete restrict,

    votos bigint not null default 0,

    percentual numeric(12,8),

    coletado_em timestamptz not null default now(),

    unique (
        eleicao_id,
        pleito_id,
        candidato_id,
        secao_id,
        raw_arquivo_id
    )
);


-- ============================================================
-- 11. FATO DE BOLETIM
-- ============================================================

create table if not exists public.fact_boletim (
    id bigint generated by default as identity primary key,

    eleicao_id bigint
        references public.dim_eleicao(id)
        on delete restrict,

    pleito_id bigint
        references public.dim_pleito(id)
        on delete restrict,

    secao_id bigint
        references public.dim_secao(id)
        on delete restrict,

    raw_arquivo_id bigint
        references public.raw_arquivos_tse(id)
        on delete restrict,

    arquivo text,

    sha256 text,

    total_votos bigint,

    status text,

    recebido_em timestamptz,

    criado_em timestamptz not null default now()
);


-- ============================================================
-- 12. AUDITORIA HISTÓRICA
-- ============================================================

create table if not exists public.fact_auditoria (
    id bigint generated by default as identity primary key,

    eleicao_id bigint
        references public.dim_eleicao(id)
        on delete restrict,

    pleito_id bigint
        references public.dim_pleito(id)
        on delete restrict,

    secao_id bigint
        references public.dim_secao(id)
        on delete restrict,

    boletim_id bigint
        references public.fact_boletim(id)
        on delete restrict,

    raw_arquivo_id bigint
        references public.raw_arquivos_tse(id)
        on delete restrict,

    status text not null,

    total_bu bigint,

    total_resultado bigint,

    divergencias jsonb not null default '[]'::jsonb,

    hash_calculado text,

    hash_armazenado text,

    criado_em timestamptz not null default now()
);


-- ============================================================
-- 13. INGESTÕES TSE
-- ============================================================

create table if not exists public.ingestoes_tse (
    id bigint generated by default as identity primary key,

    eleicao_id bigint
        references public.dim_eleicao(id)
        on delete restrict,

    tipo_arquivo text,

    url_origem text,

    idg text,

    etag text,

    last_modified text,

    sha256 text,

    iniciado_em timestamptz not null default now(),

    finalizado_em timestamptz,

    status text not null default 'iniciado'
        check (
            status in (
                'iniciado',
                'sucesso',
                'sem_alteracao',
                'erro'
            )
        ),

    registros_lidos integer default 0,

    registros_gravados integer default 0,

    erro text
);


-- ============================================================
-- ÍNDICES
-- ============================================================

create index if not exists idx_dim_pleito_eleicao
    on public.dim_pleito(eleicao_id);

create index if not exists idx_dim_municipio_uf
    on public.dim_municipio(uf_id);

create index if not exists idx_dim_zona_municipio
    on public.dim_zona(municipio_id);

create index if not exists idx_dim_secao_zona
    on public.dim_secao(zona_id);

create index if not exists idx_dim_candidato_eleicao
    on public.dim_candidato(eleicao_id);

create index if not exists idx_raw_tse_eleicao
    on public.raw_arquivos_tse(eleicao_id);

create index if not exists idx_raw_tse_tipo
    on public.raw_arquivos_tse(tipo_arquivo);

create index if not exists idx_raw_tse_recebido
    on public.raw_arquivos_tse(recebido_em);

create index if not exists idx_fact_votacao_eleicao
    on public.fact_votacao(eleicao_id);

create index if not exists idx_fact_votacao_candidato
    on public.fact_votacao(candidato_id);

create index if not exists idx_fact_votacao_municipio
    on public.fact_votacao(municipio_id);

create index if not exists idx_fact_votacao_secao
    on public.fact_votacao(secao_id);

create index if not exists idx_fact_boletim_eleicao
    on public.fact_boletim(eleicao_id);

create index if not exists idx_fact_auditoria_eleicao
    on public.fact_auditoria(eleicao_id);

create index if not exists idx_fact_auditoria_secao
    on public.fact_auditoria(secao_id);

create index if not exists idx_ingestoes_tse_eleicao
    on public.ingestoes_tse(eleicao_id);

create index if not exists idx_ingestoes_tse_iniciado
    on public.ingestoes_tse(iniciado_em);


-- ============================================================
-- 14. VIEWS PARA POWER BI
-- ============================================================

create or replace view public.vw_bi_votacao as
select
    fv.id,

    de.ano,

    de.nome as eleicao,

    de.tipo as tipo_eleicao,

    de.ambiente,

    dp.nome as pleito,

    dp.numero_turno,

    uf.sigla as uf,

    uf.nome as estado,

    mun.nome as municipio,

    z.numero as zona,

    s.numero as secao,

    c.numero as numero_candidato,

    c.nome as candidato,

    c.nome_urna,

    c.cargo,

    p.sigla as partido_sigla,

    p.nome as partido,

    fv.votos,

    fv.percentual,

    fv.coletado_em

from public.fact_votacao fv

join public.dim_eleicao de
    on de.id = fv.eleicao_id

left join public.dim_pleito dp
    on dp.id = fv.pleito_id

left join public.dim_uf uf
    on uf.id = fv.uf_id

left join public.dim_municipio mun
    on mun.id = fv.municipio_id

left join public.dim_zona z
    on z.id = fv.zona_id

left join public.dim_secao s
    on s.id = fv.secao_id

join public.dim_candidato c
    on c.id = fv.candidato_id

left join public.dim_partido p
    on p.id = c.partido_id;


-- ============================================================
-- 15. VIEW DE RESULTADO MUNICIPAL
-- ============================================================

create or replace view public.vw_bi_resultado_municipio as
select
    de.ano,

    de.nome as eleicao,

    de.ambiente,

    uf.sigla as uf,

    mun.nome as municipio,

    c.cargo,

    c.numero as numero_candidato,

    c.nome as candidato,

    p.sigla as partido_sigla,

    p.nome as partido,

    sum(fv.votos) as votos

from public.fact_votacao fv

join public.dim_eleicao de
    on de.id = fv.eleicao_id

left join public.dim_uf uf
    on uf.id = fv.uf_id

left join public.dim_municipio mun
    on mun.id = fv.municipio_id

join public.dim_candidato c
    on c.id = fv.candidato_id

left join public.dim_partido p
    on p.id = c.partido_id

group by
    de.ano,
    de.nome,
    de.ambiente,
    uf.sigla,
    mun.nome,
    c.cargo,
    c.numero,
    c.nome,
    p.sigla,
    p.nome;


-- ============================================================
-- 16. VIEW DE RESULTADO ESTADUAL
-- ============================================================

create or replace view public.vw_bi_resultado_estado as
select
    de.ano,

    de.nome as eleicao,

    de.ambiente,

    uf.sigla as uf,

    c.cargo,

    c.numero as numero_candidato,

    c.nome as candidato,

    p.sigla as partido_sigla,

    p.nome as partido,

    sum(fv.votos) as votos

from public.fact_votacao fv

join public.dim_eleicao de
    on de.id = fv.eleicao_id

left join public.dim_uf uf
    on uf.id = fv.uf_id

join public.dim_candidato c
    on c.id = fv.candidato_id

left join public.dim_partido p
    on p.id = c.partido_id

group by
    de.ano,
    de.nome,
    de.ambiente,
    uf.sigla,
    c.cargo,
    c.numero,
    c.nome,
    p.sigla,
    p.nome;


-- ============================================================
-- 17. VIEW DE AUDITORIA
-- ============================================================

create or replace view public.vw_bi_auditoria as
select
    fa.id,

    de.ano,

    de.nome as eleicao,

    de.ambiente,

    uf.sigla as uf,

    mun.nome as municipio,

    z.numero as zona,

    s.numero as secao,

    fa.status,

    fa.total_bu,

    fa.total_resultado,

    fa.total_bu -
        fa.total_resultado
        as diferenca_total,

    fa.hash_calculado,

    fa.hash_armazenado,

    fa.criado_em

from public.fact_auditoria fa

left join public.dim_eleicao de
    on de.id = fa.eleicao_id

left join public.dim_secao s
    on s.id = fa.secao_id

left join public.dim_zona z
    on z.id = s.zona_id

left join public.dim_municipio mun
    on mun.id = z.municipio_id

left join public.dim_uf uf
    on uf.id = mun.uf_id;


-- ============================================================
-- 18. VIEW DE INGESTÃO
-- ============================================================

create or replace view public.vw_bi_ingestoes as
select
    i.id,

    de.ano,

    de.nome as eleicao,

    i.tipo_arquivo,

    i.url_origem,

    i.idg,

    i.sha256,

    i.iniciado_em,

    i.finalizado_em,

    i.status,

    i.registros_lidos,

    i.registros_gravados,

    i.erro

from public.ingestoes_tse i

left join public.dim_eleicao de
    on de.id = i.eleicao_id;


-- ============================================================
-- 19. COMENTÁRIOS
-- ============================================================

comment on table public.dim_eleicao is
'Dimensão das eleições históricas e futuras.';

comment on table public.dim_pleito is
'Pleitos/turnos pertencentes a uma eleição.';

comment on table public.dim_candidato is
'Candidatos por eleição e cargo.';

comment on table public.raw_arquivos_tse is
'Conteúdo bruto dos arquivos recebidos do TSE.';

comment on table public.fact_votacao is
'Fato analítico de votação por candidato e localização.';

comment on table public.fact_boletim is
'Boletins de Urna normalizados.';

comment on table public.fact_auditoria is
'Histórico de verificações e comparações de integridade.';

comment on table public.ingestoes_tse is
'Controle operacional das ingestões realizadas no TSE.';


-- ============================================================
-- FINAL
-- ============================================================

select
    'Modelo histórico TSE criado com sucesso.' as mensagem;